#!/bin/bash
ARG TEXTBOOK_REPO_CLONE_KEY
eval `ssh-agent -s`
git config --global url."git@github.com:".insteadOf "https://github.com"
ssh-add - <<< ${TEXTBOOK_REPO_CLONE_KEY}
git submodule update --init --recursive
git config --global --remove-section url."git@github.com:"
