#!/bin/bash
ARG TEXTBOOK_REPO_CLONE_KEY
RUN eval `ssh-agent -s`
RUN git config --global url."git@github.com:".insteadOf "https://github.com"
RUN ssh-add - <<< ${TEXTBOOK_REPO_CLONE_KEY}
RUN git submodule update --init --recursive
RUN git config --global --remove-section url."git@github.com:"
